### ISSUE TITLE
Styled Components v4 Support

### ISSUE THREAD

**Issue by cneeson** [byrekt/enzyme-theme-utils#1]
Hi there, thanks for packaging up these helpers, they are awesome.

These helpers (or variants of them) have successfully been used to wrap components for testing from styled-components v2 and v3. 

The project I am currently working on is locked to the newest version of styled-components (v4), the version for which these utils don't work. 

The exact error is [here](https://github.com/byrekt/enzyme-theme-utils/blob/4fd910191d4d66da4b89d6f91f7fcf604f69b4b5/src/index.js#L16) whereby the `getChildContext` function no longer behaves.

I am wondering if you have developed any utils to solve the issue that aren't published?

Thanks!

**Comment by byrekt** [comment]
Just seeing this now but we've run into the same issue at the company I work for. Unfortunately there is some work that needs to be done on enzyme's side related to context in order for me to resolve this issue. :(

**Comment by cneeson** [comment]
No problem at all, thanks for getting back to me!

**Comment by byrekt** [comment]
@cneeson this should be resolved now. I published v3 which makes use of the wrappingComponent option added in 3.10 of enzyme.

https://github.com/styled-components/jest-styled-components/issues/256
